Database:
  Tipo: SQLITE #Tipos válidos: MYSQL_POOLING, MYSQL_PURO, MONGODB, SQLITE
  IP: localhost:3306
  DB: test
  User: admin
  Pass: ""
  Debug: true

Lista:
  - "&6eae"
  - "&5opa"

Som: BURP
Entidade: ZOMBIE
String: "&5eae"
